### PR TITLE
use getSchema method instead of static schema property

### PR DESCRIPTION
**Pull request by eiriklv**
Here's a proposal for how the issue of using props in your schema can be solved.

Refactored the tests and updated the docs/examples (might have missed something though!).

Let me know what you think :-)

### CODE REVIEW

**Comment by eiriklv** [comment]
ref #21

**Comment by eiriklv** [comment]
And as you'll see I also namespaced the `didSubmit` and `dirtyFields` on the state object

Just in case

**Comment by k88hudson** [comment]
Looks awesome, thanks for doing this :ok_hand: 

Would you mind adding a test to `CreateForm.test.jsx` for `getSchema` to check to make sure that `this.__schema` gets created as expected, maybe referencing this.props?

**Comment by k88hudson** [comment]
Also good call on namespacing

**Comment by eiriklv** [comment]
Sounds like a good idea - will do that 👍

**Comment by eiriklv** [comment]
made some really simple tests to check if `this.__schema` and `this.state` is set correctly when using `this.props` in `getSchema` to set initial values.

@k88hudson - anything else that should be added..?

**Comment by k88hudson** [comment]
Looks good to me! Many thanks :+1:

**Pull request merged**
